name: dio_http_cache_isar
description: http cache lib for Flutter dio like RxCache.It use isar as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0
authors:
  - Hurshi <ihsruh@gmail.com>
  - Eric Kok <erickok@gmail.com>
homepage: https://github.com/qunso/dio-http-cache-isar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  dio: ^4.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  path: ^1.8.0
  quiver: ^3.0.1
  isar_flutter_libs: 3.1.0+1
  isar: 3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: any
  isar_generator: 3.1.0+1
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
